# Generated by Django 2.2 on 2021-06-08 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trail', models.CharField(max_length=45)),
                ('distance', models.CharField(max_length=25)),
                ('time', models.TimeField()),
                ('notes', models.CharField(max_length=255)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ride', to='biking_app.User')),
            ],
        ),
    ]
